[project]
name = "fast-api-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.11",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
    "sqlalchemy-utils>=0.41.2",
    "uvicorn>=0.34.0",
]
