[project]
name = "ML_parquesoft"
version = "0.1.0"
description = "Introduction to AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
